# Generated by Django 5.0.2 on 2026-05-19 01:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IdentityCredential',
            fields=[
                ('vault_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('clerk_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('full_identity_name', models.CharField(blank=True, max_length=200, null=True)),
                ('registration_status', models.CharField(choices=[('WAITING', 'En Espera'), ('APPROVED', 'Acceso Concedido'), ('DENIED', 'Acceso Denegado')], default='WAITING', max_length=20)),
                ('access_level', models.CharField(choices=[('GATEKEEPER_ADMIN', 'Administrador Maestro'), ('STAFF_COORDINATOR', 'Coordinador de Staff')], default='STAFF_COORDINATOR', max_length=30)),
                ('moment_created', models.DateTimeField(auto_now_add=True)),
                ('moment_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'vault_identity_credentials',
            },
        ),
        migrations.CreateModel(
            name='VaultProfile',
            fields=[
                ('profile_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('contact_phone', models.CharField(blank=True, max_length=25, null=True)),
                ('org_unit', models.CharField(blank=True, max_length=150, null=True)),
                ('identification_code', models.CharField(blank=True, max_length=50, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('credential', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='access_vault.identitycredential')),
            ],
            options={
                'db_table': 'vault_user_profiles',
            },
        ),
    ]
