services:

  db:
    image: postgres:15-alpine
    container_name: polaris_db
    restart: always
    environment:
      POSTGRES_DB: polaris_db
      POSTGRES_USER: polaris_user
      POSTGRES_PASSWORD: polaris_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - polaris_network

  backend:
    build: ./backend
    container_name: polaris_backend
    command: >
      sh -c "
      python manage.py migrate &&
      gunicorn polaris_core.wsgi:application --bind 0.0.0.0:8000
      "
    volumes:
      - ./backend:/app
    depends_on:
      - db
    networks:
      - polaris_network

  frontend:
    build: ./frontend
    container_name: polaris_frontend
    command: npm run dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - polaris_network

  nginx:
    image: nginx:latest
    container_name: polaris_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend
    networks:
      - polaris_network

  adminer:
    image: adminer
    container_name: polaris_adminer
    ports:
      - "8080:8080"
    networks:
      - polaris_network

networks:
  polaris_network:

volumes:
  postgres_data: