# Generated by Django 5.2.12 on 2026-03-12 01:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic_workload', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('event_type', models.CharField(blank=True, max_length=60, null=True)),
                ('occurred_at', models.DateTimeField(blank=True, null=True)),
                ('processing_status', models.CharField(blank=True, max_length=20, null=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('related_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='academic_workload.comment')),
                ('related_load', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='academic_workload.academicload')),
            ],
            options={
                'db_table': 'event',
            },
        ),
        migrations.CreateModel(
            name='Eventsubscription',
            fields=[
                ('subscription_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=60)),
                ('channel', models.CharField(max_length=30)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.user')),
            ],
            options={
                'db_table': 'eventsubscription',
                'unique_together': {('user', 'event_type', 'channel')},
            },
        ),
        migrations.CreateModel(
            name='Eventdelivery',
            fields=[
                ('delivery_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('result', models.CharField(blank=True, max_length=20, null=True)),
                ('result_detail', models.TextField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='notifications.event')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='notifications.eventsubscription')),
            ],
            options={
                'db_table': 'eventdelivery',
            },
        ),
    ]
