# Generated by Django 5.0.2 on 2026-04-28 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coordinator',
            fields=[
                ('coordinator_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=120, null=True)),
                ('last_name', models.CharField(blank=True, max_length=120, null=True)),
                ('status', models.CharField(default='ACTIVE', max_length=20)),
                ('code', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.CharField(blank=True, max_length=200, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('role', models.CharField(blank=True, max_length=100, null=True)),
                ('since', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=120, unique=True)),
                ('email_notifications', models.BooleanField(default=True)),
                ('system_alerts', models.BooleanField(default=True)),
                ('weekly_report', models.BooleanField(default=False)),
                ('two_factor', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'coordinator',
                'managed': False,
            },
        ),
    ]
