# Generated by Django 5.2.12 on 2026-03-12 01:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic_career', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Period',
            fields=[
                ('period_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=40, null=True, unique=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'period',
            },
        ),
        migrations.CreateModel(
            name='Academicload',
            fields=[
                ('academic_load_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('assigned_hours', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='academic_career.teacher')),
            ],
            options={
                'db_table': 'academicload',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('source_type', models.CharField(blank=True, max_length=30, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('tag', models.CharField(blank=True, max_length=30, null=True)),
                ('academic_load', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='academic_workload.academicload')),
            ],
            options={
                'db_table': 'comment',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('section_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('section_code', models.CharField(blank=True, max_length=20, null=True)),
                ('modality', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='academic_career.course')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='academic_workload.period')),
            ],
            options={
                'db_table': 'section',
                'unique_together': {('course', 'period', 'section_code')},
            },
        ),
        migrations.AddField(
            model_name='academicload',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='academic_workload.section'),
        ),
        migrations.AlterUniqueTogether(
            name='academicload',
            unique_together={('teacher', 'section')},
        ),
    ]
