# Generated by Django 6.0.4 on 2026-04-11 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic_career', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Period',
            fields=[
                ('period_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=40, null=True, unique=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'period',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('section_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('academic_term', models.CharField(max_length=50)),
                ('section_code', models.CharField(blank=True, max_length=20, null=True)),
                ('modality', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='academic_career.course')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='academic_workload.period')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sections', to='academic_career.teacher')),
            ],
            options={
                'db_table': 'section',
                'ordering': ['name'],
                'unique_together': {('course', 'teacher', 'academic_term')},
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('sentiment_type', models.CharField(choices=[('positive', 'Positivo'), ('negative', 'Negativo')], max_length=20)),
                ('is_true_sentiment', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='comments', to='academic_workload.section')),
            ],
            options={
                'db_table': 'comment',
            },
        ),
        migrations.CreateModel(
            name='TeacherClassMetrics',
            fields=[
                ('metrics_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('positive_real', models.IntegerField(default=0)),
                ('negative_real', models.IntegerField(default=0)),
                ('false_positive', models.IntegerField(default=0)),
                ('false_negative', models.IntegerField(default=0)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('section', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='metrics', to='academic_workload.section')),
            ],
            options={
                'db_table': 'teacher_class_metrics',
            },
        ),
        migrations.CreateModel(
            name='Academicload',
            fields=[
                ('academic_load_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('assigned_hours', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='academic_career.teacher')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='academic_workload.section')),
            ],
            options={
                'db_table': 'academicload',
                'unique_together': {('teacher', 'section')},
            },
        ),
    ]
