# Generated by Django 5.2.12 on 2026-19-04
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_workload', '0001_initial'),
        ('academic_career', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='teacher',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to='academic_career.teacher',
            ),
        ),

            migrations.RemoveField(
            model_name='comment',
            name='academic_load',
        ),

        migrations.RemoveField(model_name='comment', name='source_type'),
        migrations.RemoveField(model_name='comment', name='content'),
        migrations.RemoveField(model_name='comment', name='status'),
        migrations.RemoveField(model_name='comment', name='tag'),

        migrations.AddField(
            model_name='comment',
            name='section',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to='academic_workload.section',
            ),
        ),
        migrations.AddField(
            model_name='comment',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='sentiment_type',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='is_true_sentiment',
            field=models.BooleanField(default=False),
        ),
    ]