# Generated by Django 5.0.2 on 2026-04-30 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_workload', '0002_update_schema'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='sentiment',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
