# Generated by Django 5.0.2 on 2026-04-30 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic_workload', '0003_comment_sentiment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='sentiment',
        ),
    ]
