# Generated by Django 5.0.2 on 2026-05-03 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_career', '0010_teacher_manual_status_teacher_score'),
        ('academic_workload', '0004_remove_comment_sentiment'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherCourseScore',
            fields=[
                ('score_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('final_score', models.FloatField()),
                ('criteria_scores', models.JSONField(default=dict)),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='academic_career.course')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='academic_workload.period')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='academic_career.teacher')),
            ],
            options={
                'db_table': 'teacher_course_score',
                'unique_together': {('teacher', 'course', 'period')},
            },
        ),
    ]
