# Generated by Django 6.0.4 on 2026-04-11 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('career_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=140, null=True)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'career',
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('faculty_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=120, null=True, unique=True)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'faculty',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=160, null=True)),
                ('credits', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='academic_career.career')),
            ],
            options={
                'db_table': 'course',
                'unique_together': {('career', 'name')},
            },
        ),
        migrations.AddField(
            model_name='career',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='academic_career.faculty'),
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('teacher_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=120, null=True)),
                ('last_name', models.CharField(blank=True, max_length=120, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('code', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('department', models.CharField(blank=True, max_length=200, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('role', models.CharField(choices=[('titular', 'Profesor Titular'), ('asociado', 'Profesor Asociado'), ('auxiliar', 'Profesor Auxiliar'), ('invitado', 'Profesor Invitado')], default='titular', max_length=50)),
                ('since', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, default='active', max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('courses', models.ManyToManyField(blank=True, to='academic_career.course')),
            ],
            options={
                'db_table': 'teacher',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='career',
            unique_together={('faculty', 'name')},
        ),
    ]
