# Generated by Django 5.0.2 on 2026-04-12 21:48
from django.db import migrations, models, connection


def add_fields_if_missing(apps, schema_editor):
    with connection.cursor() as cursor:
        cursor.execute("""
            SELECT column_name FROM information_schema.columns
            WHERE table_name = 'teacher'
        """)
        existing_columns = {row[0] for row in cursor.fetchall()}

        cursor.execute("""
            SELECT table_name FROM information_schema.tables
            WHERE table_name = 'teacher_courses'
        """)
        existing_tables = {row[0] for row in cursor.fetchall()}

    Teacher = apps.get_model('academic_career', 'Teacher')

    if 'code' not in existing_columns:
        schema_editor.add_field(Teacher, Teacher._meta.get_field('code'))
    if 'email' not in existing_columns:
        schema_editor.add_field(Teacher, Teacher._meta.get_field('email'))
    if 'created_at' not in existing_columns:
        schema_editor.add_field(Teacher, Teacher._meta.get_field('created_at'))
    if 'updated_at' not in existing_columns:
        schema_editor.add_field(Teacher, Teacher._meta.get_field('updated_at'))
    if 'role' not in existing_columns:
        schema_editor.add_field(Teacher, Teacher._meta.get_field('role'))
    if 'department' not in existing_columns:
        schema_editor.add_field(Teacher, Teacher._meta.get_field('department'))
    if 'phone' not in existing_columns:
        schema_editor.add_field(Teacher, Teacher._meta.get_field('phone'))
    if 'since' not in existing_columns:
        schema_editor.add_field(Teacher, Teacher._meta.get_field('since'))
    if 'teacher_courses' not in existing_tables:
        schema_editor.add_field(Teacher, Teacher._meta.get_field('courses'))


class Migration(migrations.Migration):

    dependencies = [
        ('academic_career', '0002_alter_teacher_options_teacher_code_teacher_courses_and_more'),
    ]

    operations = [
        migrations.RunPython(add_fields_if_missing, migrations.RunPython.noop),
    ]