# Generated by Django 5.0.2 on 2026-04-12 21:48
from django.db import migrations


def add_fields_if_missing(apps, schema_editor):
    # These fields are added declaratively in later migrations. Keeping this
    # operation as a no-op makes clean test database creation deterministic.
    return None


class Migration(migrations.Migration):

    dependencies = [
        ('academic_career', '0002_alter_teacher_options_teacher_code_teacher_courses_and_more'),
    ]

    operations = [
        migrations.RunPython(add_fields_if_missing, migrations.RunPython.noop),
    ]
