# Generated by Codex on 2026-04-14
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("academic_career", "0003_teacher_code_teacher_courses_teacher_created_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeacherCoordinatorOpinion",
            fields=[
                ("coordinator_opinion_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("author", models.CharField(max_length=140)),
                ("opinion", models.TextField()),
                ("rating", models.IntegerField()),
                ("opinion_date", models.DateField(blank=True, null=True)),
                ("status", models.CharField(default="active", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "teacher",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="coordinator_opinions", to="academic_career.teacher"),
                ),
            ],
            options={
                "db_table": "teacher_coordinator_opinion",
                "ordering": ["teacher_id", "-opinion_date", "-created_at"],
                "unique_together": {("teacher", "author", "opinion", "opinion_date")},
            },
        ),
        migrations.CreateModel(
            name="TeacherMerit",
            fields=[
                ("merit_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("merit_type", models.CharField(max_length=140)),
                ("description", models.TextField()),
                ("obtained_at", models.DateField(blank=True, null=True)),
                ("granting_institution", models.CharField(max_length=180)),
                ("status", models.CharField(default="active", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "teacher",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="merits", to="academic_career.teacher"),
                ),
            ],
            options={
                "db_table": "teacher_merit",
                "ordering": ["teacher_id", "-obtained_at", "-created_at"],
                "unique_together": {("teacher", "merit_type", "description", "obtained_at", "granting_institution")},
            },
        ),
        migrations.CreateModel(
            name="TeacherStudentSurvey",
            fields=[
                ("survey_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("author", models.CharField(max_length=140)),
                ("opinion", models.TextField()),
                ("rating", models.IntegerField()),
                ("opinion_date", models.DateField(blank=True, null=True)),
                ("status", models.CharField(default="active", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "teacher",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="student_surveys", to="academic_career.teacher"),
                ),
            ],
            options={
                "db_table": "teacher_student_survey",
                "ordering": ["teacher_id", "-opinion_date", "-created_at"],
                "unique_together": {("teacher", "author", "opinion", "opinion_date")},
            },
        ),
        migrations.CreateModel(
            name="TeacherTitle",
            fields=[
                ("title_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("phone", models.CharField(blank=True, max_length=30, null=True)),
                ("specialty", models.CharField(max_length=140)),
                ("academic_degree", models.CharField(max_length=140)),
                ("experience_years", models.IntegerField(default=0)),
                ("current_institution", models.CharField(max_length=180)),
                ("status", models.CharField(default="active", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "teacher",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="titles", to="academic_career.teacher"),
                ),
            ],
            options={
                "db_table": "teacher_title",
                "ordering": ["teacher_id", "-created_at"],
                "unique_together": {("teacher", "specialty", "academic_degree", "current_institution")},
            },
        ),
    ]
