# Generated by Django 5.0.2 on 2026-04-15 01:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_career', '0003_teacher_code_teacher_courses_teacher_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='role',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='TeacherCourse',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('course', models.ForeignKey(db_column='course_id', on_delete=django.db.models.deletion.DO_NOTHING, to='academic_career.course')),
                ('teacher', models.ForeignKey(db_column='teacher_id', on_delete=django.db.models.deletion.DO_NOTHING, to='academic_career.teacher')),
            ],
            options={
                'db_table': 'teacher_courses',
                'unique_together': {('teacher', 'course')},
            },
        ),
        migrations.AddField(
            model_name='teacher',
            name='courses',
            field=models.ManyToManyField(blank=True, through='academic_career.TeacherCourse', to='academic_career.course'),
        ),
    ]
