# Generated by Django 5.0.2 on 2026-04-15 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic_career', '0004_teachercoordinatoropinion_teachermerit_teachersurvey_and_more'),
        ('academic_career', '0005_teacher_department_teacher_phone_teacher_since_and_more'),
    ]

    operations = [
    ]
