# Generated by Codex on 2026-04-23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic_career", "0008_teacherstudentsurvey_course_and_section"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teacherstudentsurvey",
            name="rating",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
