# Generated by Django 5.0.2 on 2026-04-30 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_career', '0009_teacherstudentsurvey_rating_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='manual_status',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
