# Generated by Django 6.0.4 on 2026-04-11 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluationcriterion',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('criterion_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('display_order', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'evaluationcriterion',
                'ordering': ['display_order', 'criterion_id'],
            },
        ),
        migrations.CreateModel(
            name='Weightconfig',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('weight_config_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Activo'), ('inactive', 'Inactivo')], default='inactive', max_length=20)),
            ],
            options={
                'db_table': 'weightconfig',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WeightconfigCriterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=6)),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='weight_configs', to='assessment_360.evaluationcriterion')),
                ('weight_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria_weights', to='assessment_360.weightconfig')),
            ],
            options={
                'db_table': 'weightconfig_criterion',
                'unique_together': {('weight_config', 'criterion')},
            },
        ),
    ]
