# Generated by Django 5.0.2 on 2026-02-21 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic_workload', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluationcriterion',
            fields=[
                ('criterion_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=80, null=True, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('display_order', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'evaluationcriterion',
            },
        ),
        migrations.CreateModel(
            name='Weightconfig',
            fields=[
                ('weight_config_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=120, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='academic_workload.period')),
            ],
            options={
                'db_table': 'weightconfig',
            },
        ),
        migrations.CreateModel(
            name='WeightconfigCriterion',
            fields=[
                ('weight_config', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='assessment_360.weightconfig')),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='assessment_360.evaluationcriterion')),
            ],
            options={
                'db_table': 'weightconfig_criterion',
                'unique_together': {('weight_config', 'criterion')},
            },
        ),
    ]
