# Generated by Django 5.0.2 on 2026-03-26 01:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluationcriterion',
            fields=[
                ('criterion_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=80, null=True, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('display_order', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'evaluationcriterion',
            },
        ),
        migrations.CreateModel(
            name='Weightconfig',
            fields=[
                ('weight_config_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=120, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'weightconfig',
            },
        ),
        migrations.CreateModel(
            name='WeightconfigCriterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessment_360.evaluationcriterion')),
                ('weight_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessment_360.weightconfig')),
            ],
            options={
                'db_table': 'weightconfig_criterion',
                'unique_together': {('weight_config', 'criterion')},
            },
        ),
    ]
