# Generated by Django 5.0.2 on 2026-04-06 05:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment_360', '0002_evaluationcriterion_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weightconfig',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
