# Generated by Django 5.0.2 on 2026-04-06 06:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment_360', '0005_drop_period_id_not_null'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evaluationcriterion',
            options={'ordering': ['display_order', 'criterion_id']},
        ),
        migrations.AlterModelOptions(
            name='weightconfig',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='weightconfigcriterion',
            options={'managed': False},
        ),
        migrations.AlterField(
            model_name='evaluationcriterion',
            name='display_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='evaluationcriterion',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=80, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='weightconfig',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=120),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='weightconfig',
            name='status',
            field=models.CharField(choices=[('active', 'Activo'), ('inactive', 'Inactivo')], default='inactive', max_length=20),
        ),
    ]
