# Generated by Django 5.0.2 on 2026-04-06 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessment_360', '0007_add_id_to_weightconfig_criterion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weightconfigcriterion',
            options={},
        ),
    ]
