# Generated by Django 5.0.2 on 2026-04-15 01:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment_360', '0008_weightconfig_criterion_managed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weightconfigcriterion',
            name='criterion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='weight_configs', to='assessment_360.evaluationcriterion'),
        ),
        migrations.AlterField(
            model_name='weightconfigcriterion',
            name='percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='weightconfigcriterion',
            name='weight_config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria_weights', to='assessment_360.weightconfig'),
        ),
    ]
