# Generated by Django 5.0.2 on 2026-05-13 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic_career', '0010_teacher_manual_status_teacher_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=80, null=True, unique=True)),
                ('password_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, choices=[('active', 'Activo'), ('inactive', 'Inactivo'), ('suspended', 'Suspendido')], default='active', max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'User',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Coordinator',
            fields=[
                ('coordinator_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=120, null=True)),
                ('last_name', models.CharField(blank=True, max_length=120, null=True)),
                ('status', models.CharField(blank=True, choices=[('active', 'Activo'), ('inactive', 'Inactivo')], default='active', max_length=20, null=True)),
                ('code', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('department', models.CharField(blank=True, max_length=200, null=True)),
                ('role', models.CharField(blank=True, max_length=100, null=True)),
                ('since', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coordinator', to='accounts.user')),
            ],
            options={
                'verbose_name': 'Coordinador',
                'verbose_name_plural': 'Coordinadores',
                'db_table': 'coordinator',
            },
        ),
        migrations.CreateModel(
            name='CoordinatorCareer',
            fields=[
                ('coordinator', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accounts.coordinator')),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic_career.career')),
            ],
            options={
                'verbose_name': 'Coordinador - Carrera',
                'verbose_name_plural': 'Coordinadores - Carreras',
                'db_table': 'coordinator_career',
                'unique_together': {('coordinator', 'career')},
            },
        ),
        migrations.CreateModel(
            name='CoordinatorFaculty',
            fields=[
                ('coordinator', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accounts.coordinator')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic_career.faculty')),
            ],
            options={
                'verbose_name': 'Coordinador - Facultad',
                'verbose_name_plural': 'Coordinadores - Facultades',
                'db_table': 'coordinator_faculty',
                'unique_together': {('coordinator', 'faculty')},
            },
        ),
    ]
