# Generated by Django 5.2.12 on 2026-03-12 01:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic_career', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=80, null=True, unique=True)),
                ('password_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'User',
            },
        ),
        migrations.CreateModel(
            name='Coordinator',
            fields=[
                ('coordinator_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=120, null=True)),
                ('last_name', models.CharField(blank=True, max_length=120, null=True)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.user')),
            ],
            options={
                'db_table': 'coordinator',
            },
        ),
        migrations.CreateModel(
            name='CoordinatorCareer',
            fields=[
                ('coordinator', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='accounts.coordinator')),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='academic_career.career')),
            ],
            options={
                'db_table': 'coordinator_career',
                'unique_together': {('coordinator', 'career')},
            },
        ),
        migrations.CreateModel(
            name='CoordinatorFaculty',
            fields=[
                ('coordinator', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='accounts.coordinator')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='academic_career.faculty')),
            ],
            options={
                'db_table': 'coordinator_faculty',
                'unique_together': {('coordinator', 'faculty')},
            },
        ),
    ]
