# Generated by Django 5.0.2 on 2026-04-16 01:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_career', '0006_merge_20260415_1000'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coordinator',
            options={'verbose_name': 'Coordinador', 'verbose_name_plural': 'Coordinadores'},
        ),
        migrations.AlterModelOptions(
            name='coordinatorcareer',
            options={'verbose_name': 'Coordinador - Carrera', 'verbose_name_plural': 'Coordinadores - Carreras'},
        ),
        migrations.AlterModelOptions(
            name='coordinatorfaculty',
            options={'verbose_name': 'Coordinador - Facultad', 'verbose_name_plural': 'Coordinadores - Facultades'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AlterField(
            model_name='coordinator',
            name='status',
            field=models.CharField(blank=True, choices=[('active', 'Activo'), ('inactive', 'Inactivo')], default='active', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='coordinator',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coordinator', to='accounts.user'),
        ),
        migrations.AlterField(
            model_name='coordinatorcareer',
            name='career',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic_career.career'),
        ),
        migrations.AlterField(
            model_name='coordinatorcareer',
            name='coordinator',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accounts.coordinator'),
        ),
        migrations.AlterField(
            model_name='coordinatorfaculty',
            name='coordinator',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accounts.coordinator'),
        ),
        migrations.AlterField(
            model_name='coordinatorfaculty',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic_career.faculty'),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(blank=True, choices=[('active', 'Activo'), ('inactive', 'Inactivo'), ('suspended', 'Suspendido')], default='active', max_length=20, null=True),
        ),
    ]
