# Generated by Django 5.0.2 on 2026-05-19 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_coordinator_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'managed': True, 'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
    ]
