# Generated by Django 5.0.2 on 2026-05-14 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationTemplate',
            fields=[
                ('template_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'evaluation_template',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TemplateDimension',
            fields=[
                ('dimension_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('weight', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dimensions', to='templates.evaluationtemplate')),
            ],
            options={
                'db_table': 'template_dimension',
            },
        ),
        migrations.CreateModel(
            name='TemplateQuestion',
            fields=[
                ('question_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('question_type', models.CharField(default='likert', max_length=50)),
                ('dimension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='templates.templatedimension')),
            ],
            options={
                'db_table': 'template_question',
            },
        ),
    ]
