# Generated by Django 5.0.2 on 2026-05-14 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_career', '0010_teacher_manual_status_teacher_score'),
        ('templates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherEvaluation',
            fields=[
                ('evaluation_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('semester', models.CharField(max_length=50)),
                ('section', models.CharField(max_length=50)),
                ('period', models.CharField(blank=True, max_length=100, null=True)),
                ('final_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('observations', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academic_career.course')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='academic_career.teacher')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='templates.evaluationtemplate')),
            ],
            options={
                'db_table': 'teacher_evaluation',
            },
        ),
        migrations.CreateModel(
            name='EvaluationAnswer',
            fields=[
                ('answer_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('value_numeric', models.IntegerField(blank=True, null=True)),
                ('value_text', models.TextField(blank=True, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='templates.templatequestion')),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='templates.teacherevaluation')),
            ],
            options={
                'db_table': 'evaluation_answer',
            },
        ),
    ]
