# Generated by Django 5.0.2 on 2026-03-12 02:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BulkUploadBatch',
            fields=[
                ('batch_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('titulos', 'Titulos'), ('meritos', 'Meritos'), ('opiniones', 'Opiniones')], max_length=20)),
                ('source_filename', models.CharField(max_length=255)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('valid_rows', models.PositiveIntegerField(default=0)),
                ('invalid_rows', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processed', 'Processed'), ('processed_with_errors', 'Processed with errors'), ('failed', 'Failed')], default='pending', max_length=30)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'bulk_upload_batch',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BulkUploadRecord',
            fields=[
                ('record_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('row_number', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('valid', 'Valid'), ('invalid', 'Invalid')], max_length=20)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('normalized_data', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(db_column='batch_id', on_delete=django.db.models.deletion.CASCADE, related_name='records', to='integrations.bulkuploadbatch')),
            ],
            options={
                'db_table': 'bulk_upload_record',
                'ordering': ['record_id'],
            },
        ),
    ]
